### ISSUE TITLE
Feature request: kindly explain better wtf this is

### ISSUE THREAD

**Issue by ziffusion** [icholy/rip#1]

**Comment by icholy** [comment]
I added another section to the readme

> Parse lines from stdin using regular expressions. Then reformat them using a pattern (template).

**Comment by ziffusion** [comment]
Paying more attention, now I see what you are doing.

Just a suggestion. Both the name and description don't convey  the function adequately. And that's what most people look at first. A nonsensical description turns people off.

Here are some alternatives for description:

1. Transform input using regular expressions.
1. Use regular expressions to edit the input.

**Comment by icholy** [comment]
@ziffusion do you think that's good enough? Got some suggestions?

**Comment by ziffusion** [comment]
Still a bit confusing if you ask me. To me something like the following sounds better - but that's just me.

"Transform input text using regular expression substitutions"

Then you could explain below in more detail how one would do that i.e. using a substitution syntax that uses captures from the regular expressions etc.

Usage: 

rip `<regular expression>` `<substitution pattern>`
