### ISSUE TITLE
the choice of $ was a bad one for a command line application

### ISSUE THREAD

**Issue by Ghoughpteighbteau** [icholy/rip#3]
running this command will break in a confusing way `rip "psudoGrep" "$line"`

because most command lines will try to substitute `$line` with the variable `line` in double quotes.

would you consider maybe using '#' instead?

**Comment by icholy** [comment]
I was thinking `%`.

**Comment by Ghoughpteighbteau** [comment]
also good.

**Comment by icholy** [comment]
@Ghoughpteighbteau I don't think `#` is a good idea because that starts a comment in bash.

**Comment by icholy** [comment]
@Ghoughpteighbteau can you test out the `new_prefix` branch?

**Comment by Ghoughpteighbteau** [comment]
the comment symbol isn't much of an issue because regex usually require quotation marks, plus if there is any whitespace it would be interpreted as multiple arguments, so those are pretty much always gonna be there.

Not many good options here. Perl uses `$`, and vim and emacs use `\` which obviously isn't any better. I feel like # is easier to reach, but that might be a quibble. 

anyway. 

```
tylers-laptop@~/s/rip-change-prefix $ ls | ./rip "(rip)" '%debug'
rip
---
%0 = rip
%1 = rip

rip.go
------
%0 = rip
%1 = rip

tylers-laptop@~/s/rip-change-prefix $ ls | ./rip "(rip)" '%line'
rip
rip.go
tylers-laptop@~/s/rip-change-prefix $ ls | ./rip "(rip)" '%1'
rip
rip
tylers-laptop@~/s/rip-change-prefix $ ls | ./rip "(rip)" '%%1'
%rip
%rip
```

problem with that last one. I expected %1 as output.

**Comment by icholy** [comment]
@Ghoughpteighbteau thanks for testing it out. I'll try to get it fixed sometime soon.

**Comment by icholy** [comment]
@Ghoughpteighbteau I'm on and off messing around with writing a parser for this. For isolating identifiers, I still have to support `%{ident}` syntax which `printf` format string doesn't do. There's also no support for formatting based on type `%d` `%f`. So Idk if it's even worth following the `%%` convention as opposed to escaping it `\%` like it works now.

**Comment by Ghoughpteighbteau** [comment]
Oh I didn't even know you could escape them. I assumed %% was the escape. \% is fine by me as long as it's documented. 

%{ident} would be a good feature. I actually hit a situation where I was using rip to mass rename files, and I was extracting and placing some dates and the identifier was up against a number. 

anyway, never mind on the %%.

**Comment by icholy** [comment]
`%{ident}` should already work.

**Comment by icholy** [comment]
@Ghoughpteighbteau I'm thinking that instead of changing the behaviour, I'll introduce another environment variable called `RIP_PREFIX` which can be set to either `$`, `%`, or `#`. It will still default to `$` so that it doesn't breaking backwards compatibility. Sound good?

**Comment by Ghoughpteighbteau** [comment]
I'll be honest, I have an ingrained fear of changing defaults. Sometimes programs only ever get tested against the defaults, and changing those defaults might break something. When you're a new user, the last thing you want is a problem that can't be reproduced by experienced users.

It sucks changing the symbol and breaking any scripts that depend on it, but that $ symbol is annoying, and you don't exactly have a legion of users, you're not sed yet! I'd pull that bandaid now if I was you.

Just my thoughts on the matter. I can live with an environment variable. :+1:

**Comment by icholy** [comment]
Thing is, I like the `$` and IMO it's no more dangerous than the `*` that are required in the regex parameter.

**Comment by icholy** [comment]
@Ghoughpteighbteau ok, I've made the changes. Want to test it out? I'm about to make another release.
