### ISSUE TITLE
Match multiple separate spaces?

### ISSUE THREAD

**Issue by Jimmie-Cricket** [icholy/rip#5]
I'm trying out this cool utility and I used it to rename files with underscores to dashes and could debug with a simple command like:
```shell
ls|rip '(.*)_(.*)' 'mv "$0" "$1-$2"'|cat -
ls|rip '(.*)_(.*)' 'mv "$0" "$1-$2"'|sh -
``` 
Now I have some files that have multiple spaces but I can't seem to get a regex to work the file names can have one or more spaces like:
```
'Efficient Embedded Design.pdf'           'Introduction To Ada.pdf'
'Hands-On RTOS with Microcontrollers.odt' 'Mastering Embedded Linux Programming 3rd.odt'   
```
So I'm wondering if matches like this are possible with rip.
Thanks for any help.

**Comment by icholy** [comment]
Would something like this work? `rip '^(.*)\.(\w+)$'`

**Comment by Jimmie-Cricket** [comment]
Hmm, couldn't seem to get this to work.  However, I was able to work the original example I posted and just loop a few times until all spaces are replaced.  A little hacky and inefficient but gets the job done.
Thanks for the help.

**Comment by icholy** [comment]
Sorry, I'm still unclear on what you're trying to accomplish.

**Comment by Jimmie-Cricket** [comment]
Sorry for not being more clear.  I was trying to use `ls|rip` to replace all spaces in a filename with a '-' or '_'.

**Comment by icholy** [comment]
Ah ok, yeah that's not possible.
